### ISSUE TITLE
Collapsible menu issues

### ISSUE THREAD

**Issue by twinser** [SpectoLabs/mirage#39]
The collapsible menu on the left has some minor issues. You may be aware of these, but I thought I'd raise them anyway:
- When the menu is collapsed, the version text is still visible over the top. 
- The version number is highlighted and shows a hand when you hover over it, indicating it is a clickable link. It doesn't go anywhere
- As above, but for "Examples"
- When collapsed, it is impossible to enable full tracking or all hosts due to the speech bubble being in the way (see image below)

![image](https://cloud.githubusercontent.com/assets/6523398/10540213/06f5b18a-73fe-11e5-8ae5-500ff93fe911.png)

**Comment by rusenask** [comment]
Hi,
Thanks, collapse issue fixed in https://github.com/SpectoLabs/mirage/commit/82a161231486afe687259dbcec2cfb65ddbc0e14
and will be in master some time soon. As for hovering - it's due to theme style and you can't get away from using <a/> elements there. Maybe creating another css class for those two elements would be a solution.

**Comment by twinser** [comment]
Ah yes, perfect.
Yes, that sounds like a good solution to me. :)

**Comment by JohnFDavenport** [comment]
@twinser could you do me a favour and have a look at 0.8.3 and comment how this now looks and report on remaining issues please, old chum!

**Comment by JohnFDavenport** [comment]
Just had a look. These problems have been fixed.

- [x] - The version has been moved
- [x] - Full tracking and All hosts are selectable even when menu collapsed

**Comment by twinser** [comment]
Sorry @JohnFDavenport - I didn't see your message until just now, but I note that you've looked into it yourself 😄
