### ISSUE TITLE
Bug in date rolling

### ISSUE THREAD

**Issue by JohnFDavenport** [SpectoLabs/mirage#7]
Issue raised:
Attaching a test case of date rolling of repeated elements (new feature). Dates included in the response are 2014-06-08, 2014-06-09 and 2014-06-06 [YYYY-MM-DD]

For a date delta of 2 days :

2014-06-08 rolls to 2014-06-10 
2014-06-09 rolls to 2014-06-11 
2014-06-06 rolls to 2014-08-06 (it should have rolled forward to 2014-06-08)

**Comment by JohnFDavenport** [comment]
The problem appears to be because [Pandas](https://github.com/pydata/pandas/blob/master/pandas/tseries/tools.py) is being used. That is a fine library but it is really aimed at data munging (e.g. the territory of BeautifulSoup) where you have a lot of text data, no schema but there is a value in manipulating the data. In particular, you might have dates but the dates may vary from data item to data item, or may even vary between separate instances of a data item. In this case we have an XML and we therefore know what kind of date to expect. strftime and strptime have some good lexical elements for making use of such dates and so we could end up with a far simpler solution by using them.

**Comment by shyal** [comment]
Fixed. Shall be part of next release.
