### ISSUE TITLE
Bug in template replacement

### ISSUE THREAD

**Issue by roopeshpraj** [SpectoLabs/mirage#79]
Just spotted a potential bug in template replacement. Template replacement is not happening when there are multiple matchers. 

1) Multiple matchers no template replacement (Works as expected)
request -
<something>some</something><rollMe>11Dec15</rollMe>
matcher 1
<something>some</something>
matcher 2
<rollMe>11Dec15</rollMe>

2) Single matcher with template replacement (Works as expected, template replacement occurs)
request -
<something>some</something><rollMe>11Dec15</rollMe>
matcher
{% import datetime %}
{% set yy = str(datetime.datetime.now().year)[2:] %}
{% set mm = datetime.datetime.now().strftime('%b') %}
{% set dd = '%02d' % datetime.datetime.now().day %}
<rollMe>{{dd}}{{mm}}{{yy}}</rollMe>

3) Multiple matchers with template replacement (template replacement is not occuring in this case - testcase attached)
request -
<something>some</something><rollMe>11Dec15</rollMe>
matcher 1
<something>some</something>
matcher 2
{% import datetime %}
{% set yy = str(datetime.datetime.now().year)[2:] %}
{% set mm = datetime.datetime.now().strftime('%b') %}
{% set dd = '%02d' % datetime.datetime.now().day %}
<rollMe>{{dd}}{{mm}}{{yy}}</rollMe>

[first.commands.txt](https://github.com/SpectoLabs/mirage/files/59505/first.commands.txt)
[first.matcher.txt](https://github.com/SpectoLabs/mirage/files/59504/first.matcher.txt)
[first.request.txt](https://github.com/SpectoLabs/mirage/files/59503/first.request.txt)
[first.response.txt](https://github.com/SpectoLabs/mirage/files/59506/first.response.txt)
[initial.matcher.txt](https://github.com/SpectoLabs/mirage/files/59502/initial.matcher.txt)

**Comment by JohnFDavenport** [comment]
Thank you Roopesh. The attachments will help me to reproduce the problem.

1. Which version(s) of Mirage have you tried this on?
2. Has this ever worked before as far as you know?
3. I notice that the month is encoded one way `datetime.datetime.now().strftime('%b')`, but the year is encoded as `str(datetime.datetime.now().year)[2:]` rather than `datetime.datetime.now().strftime('%y')`. Is there any reason for that?

**Comment by roopeshpraj** [comment]
1) Mirage 0.8.2

2) Haven't checked this before

3) No. Any template replacement chunk should do. For the following example will also fail -

request - <something>some</something><rollMe>XYZ</rollMe>

matcher1 -
<something>some</something>

matcher2-
{% set x = 'XYZ' %}
<rollMe>{{x}}</rollMe>

**Comment by shyal** [comment]
I noticed that in ```first.commands.txt``` you've got multiple matches on one line.

```
put/stub?session=first_1,initial.matcher,first.matcher,first.response
```

Is this valid syntax for a put/stub command? Here's the equivalent, but with only one matcher per line:

```url
delete/stubs?scenario=first
begin/session?scenario=first&session=first_1&mode=record
put/stub?session=first_1,initial.matcher,first.response
put/stub?session=first_1,first.matcher,first.response
end/session?session=first_1

begin/session?scenario=first&session=first_2&mode=playback
get/response?session=first_2, first.request
end/session?session=first_2
```

And here's the response, with all success codes.

```json
{
    "version": "0.8.3",
    "data": {
        "executed_commands": {
            "commands": [
                ["delete/stubs?scenario=first", 200],
                ["begin/session?scenario=first&session=first_1&mode=record", 200],
                ["put/stub?session=first_1,initial.matcher,first.response", 200],
                ["put/stub?session=first_1,first.matcher,first.response", 200],
                ["end/session?session=first_1", 200],
                ["begin/session?scenario=first&session=first_2&mode=playback", 200],
                ["get/response?session=first_2, first.request", 200],
                ["end/session?session=first_2", 200]
            ]
        },
        "number_of_requests": 8,
        "number_of_errors": 0
    }
}
```

Does this solve your issue? I'll continue investigating either way.

**Comment by shyal** [comment]
Just to confirm I've written a unit test for those case scenario, and when my requests are either:

```
<something>some</something>
```

or

```
<rollMe>%s%s%s</rollMe>
```
(with today's date)

then in both cases I get this in the response:

```
The flight number is: XX1234
Hello World 1013
```

The unit test is passing, with the modified content of ```first.commands.txt``` I included in my previous comment. So to me, this seems to be working. The issue may have come from unclear documentation? Or maybe I've misunderstood the issue.

Regards.

**Comment by roopeshpraj** [comment]
>>put/stub?session=first_1,initial.matcher,first.matcher,first.response
Yes this is a valid case. Please see the attached example scenario with multiple matchers :  
[mutiple-matchers-without-templates-sl.zip](https://github.com/SpectoLabs/mirage/files/578557/mutiple-matchers-without-templates-sl.zip)

**Comment by roopeshpraj** [comment]
Failing test of mutiple-matchers-with-templates. (Only difference from mutiple-matchers-without-templates-sl.zip is the use of templating) 

(https://github.com/SpectoLabs/mirage/files/578753/mutiple-matchers-with-templates-sl.zip)

**Comment by shyal** [comment]
Does this work the same?

```
put/stub?session=first_1,initial.matcher,first.response
put/stub?session=first_1,first.matcher,first.response
```

as this?

```
put/stub?session=first_1,initial.matcher,first.response
put/stub?session=first_1,first.matcher,first.response
```

And if so, then what's the issue just breaking it up in two lines instead of having it in one line? Where did you get this example from? The documentation or did you write it yourself?

**Comment by roopeshpraj** [comment]
Thanks. I will try this out and get back to you.

**Comment by shyal** [comment]
Ah OK I've been digging deeper into this issue. Sorry indeed multiple matching does not work. I got it to work with non-templated responses, by looking for the best match. However this does not work yet with templated responses.

I'll also need to see how this affects performance before checking the code in. In essence I'm checking every request against every stub instead of returning the first match. This definitely will take a hit on performance, so will have to think of a graceful way of implementing this without impacting existing functionality.

**Comment by JohnFDavenport** [comment]
Performance is essential to SIP Mirage users so we need to be careful.

**Comment by rusenask** [comment]
hey guys, I think you should treat this multi matching as a full text search. Pure Python equivalent would be Whoosh  https://pypi.python.org/pypi/Whoosh/, it would solve oldest mirage's problem regarding extremely underperforming matching engine

**Comment by shyal** [comment]
Hi Koralis. Yes whoosh is great. Thanks for the suggestion, we'll consider it.

**Comment by shyal** [comment]
Fixed. Shall be part of next release.
