### ISSUE TITLE
dead link to demo project in wiki

### ISSUE THREAD

**Issue by shyal** [SpectoLabs/mirage#92]
On https://github.com/SpectoLabs/mirage/wiki/Introduction dead link at the bottom of the document: "Try the Mirage Demo -> https://github.com/SpectoLabs/mirage_demo"

**Comment by JohnFDavenport** [comment]
Thanks for reporting this and any other issue.

**Comment by shyal** [comment]
Note: this is not a dead link, however this repo has been set to private.

**Comment by shyal** [comment]
I recommend we change the settings on this repo for it to be public, as opposed to private: https://github.com/SpectoLabs/mirage_demo

**Comment by JohnFDavenport** [comment]
Now all done.
