### ISSUE TITLE
Remove Docker and Tutum installation from documentation

### ISSUE THREAD

**Issue by JohnFDavenport** [SpectoLabs/mirage#98]
The Docker and Tutum installation instructions are out of date and in any case are problematic. The manual installation processes are quick enough. The following changes need to be made:

- [x] Remove the **Docker** section under **OSX** from https://github.com/SpectoLabs/mirage/wiki/Installation
- [x] Remove the **Deploy to Tutum** button from https://github.com/SpectoLabs/mirage and the preceding paragraph
- [x] Change the text "For the less impatient" to "The Mirage server can be installed in 30 minutes or less "

**Comment by shyal** [comment]
Done.
